name: hotspot
description: Simple tours, coachmarks, and tutorials. Just tag your Widgets!
version: 0.1.3
repository: https://github.com/lukepighetti/flutter_hotspot

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
